name: Native Image
on:
  push:
jobs:
  # unix:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, macOS-latest]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: olafurpg/setup-scala@v2
  #       with:
  #         java-version: graalvm@
  #     - name: Link native image
  #       run: |
  #         gu install native-image
  #         csbt plugin/graalvm-native-image:packageBin
  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: plugin
  #         path: plugin/target/graalvm-native-image/plugin
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Link native image
        shell: bash
        run: |
          # Remove-Item –path 'C:\Program Files (x86)\Microsoft Visual Studio\' -Filter *test* -whatif
          # rm -rf "/C/Program Files (x86)/Microsoft Visual Studio"
          # rm -rf "/C/Program Files/Microsoft Visual Studio"
          # # doesn't work yet (even locally)
          choco install -y mingw vcbuildtools windows-sdk-7.1 || true
          # find "/C/Program Files/Microsoft SDKs/Windows/v7.1" | sort
          export PATH="/C/Program Files/Microsoft SDKs/Windows/v7.1/Bin/x64:/C/Program Files/Microsoft SDKs/Windows/v7.1/Bin:$PATH"
          curl -Lo graalvm.zip https://github.com/oracle/graal/releases/download/vm-19.1.1/graalvm-ce-windows-amd64-19.1.1.zip
          unzip graalvm.zip
          GRAALVM_HOME="$(pwd)/graalvm-ce-19.1.1"
          # no JDK on Travis CI Windows, using graal's java too
          export PATH="$GRAALVM_HOME/bin:$PATH"
          export NATIVE_IMAGE="$GRAALVM_HOME/bin/native-image.cmd"
          java -Xss2m -Xmx4096m -XX:-TieredCompilation -XX:ReservedCodeCacheSize=48m -Dfile.encoding=UTF-8 -Djna.nosys=true -jar sbt-launch.jar plugin/nativeWindowsImage
      - uses: actions/upload-artifact@master
        with:
          name: plugin
          path: plugin/target/graalvm-native-image/plugin.exe
