name: Native Image
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
        with:
          java-version: graalvm@
      - name: Compile
        run: |
          gu install native-image
          java -Xss2m -Xmx4096m -XX:-TieredCompilation -XX:ReservedCodeCacheSize=48m -Dfile.encoding=UTF-8 -Djna.nosys=true -jar sbt-launch.jar plugin/graalvm-native-image:packageBin
      - uses: actions/upload-artifact@master
        with:
          name: plugin
          path: plugin/target/graalvm-native-image/plugin
