name: Native Image
on:
  push:
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
        with:
          java-version: graalvm@
      - name: Link native image
        run: |
          gu install native-image
          csbt plugin/graalvm-native-image:packageBin
      - uses: actions/upload-artifact@master
        with:
          name: plugin
          path: plugin/target/graalvm-native-image/plugin
