name: Release
on:
  push:
    branches: [master]
    tags:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v2
    - name: Publish
      run: csbt ci-release